CXXFLAGS+=-Iinclude/rt/virgil
CXXFLAGS+=-std=c++14 -g -fno-inline -fno-omit-frame-pointer -mno-tls-direct-seg-refs

# obj-y += queue/
obj-y += pool/

# all: pool queue

# pool:
# 	cd $@ ; make ;

# queue:
# 	cd $@ ; make ;

# clean:
# 	cd pool ; make clean ;
# 	cd queue ; make clean ; 

# .PHONY: pool queue
